name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install dependencies and Android SDK tools
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git zip openjdk-17-jdk wget unzip
        pip install buildozer cython

        # Download Android SDK command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

        # Export environment variables for later steps
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install Android build-tools
      run: |
        sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        buildozer android debug
